/**
 * @file UuidGenerator.ts
 * @author Dominic Rodemer
 * @created 2025-12-11
 * @license MIT
 */

/**
 * UUID Generator for Apple DocC cache lookup
 *
 * Generates UUIDs that map request keys to cache.db entries.
 * Apple uses a specific algorithm: SHA-1 hash of the canonical path,
 * truncated to 6 bytes and base64url encoded, with a language prefix.
 *
 * @module extractor/UuidGenerator
 */

import { createHash } from 'node:crypto';

/**
 * Generate a UUID for cache lookup from a request key.
 *
 * The UUID is generated by:
 * 1. Creating a canonical path from the request key
 * 2. Computing SHA-1 hash of the path
 * 3. Truncating to first 6 bytes
 * 4. Base64url encoding
 * 5. Prepending language prefix (ls for Swift, lc for Objective-C)
 *
 * @param requestKey - Request key from docSet.dsidx (e.g., "ls/documentation/uikit/uiwindow")
 * @returns UUID for cache.db lookup (e.g., "lsXYZ123")
 * @throws Error if request key format is invalid
 *
 * @example
 * ```typescript
 * const uuid = generateUuid('ls/documentation/uikit/uiwindow');
 * // Returns something like "lsABC123..."
 * ```
 */
export function generateUuid(requestKey: string): string {
  // Determine language prefix and extract canonical path
  let prefix: string;
  let canonicalPath: string;

  if (requestKey.startsWith('ls/')) {
    prefix = 'ls';
    canonicalPath = '/' + requestKey.slice(3);
  } else if (requestKey.startsWith('lc/')) {
    prefix = 'lc';
    canonicalPath = '/' + requestKey.slice(3);
  } else {
    throw new Error(`Invalid request key format: ${requestKey}`);
  }

  // Compute SHA-1 hash
  const hash = createHash('sha1').update(canonicalPath).digest();

  // Truncate to first 6 bytes and encode as base64url
  const truncated = hash.subarray(0, 6);
  const suffix = truncated.toString('base64url');

  return prefix + suffix;
}

/**
 * Extract the documentation path from a request key.
 * Removes the language prefix and adds a leading slash.
 *
 * @param requestKey - Request key (e.g., "ls/documentation/accelerate")
 * @returns Canonical path (e.g., "/documentation/accelerate")
 *
 * @example
 * ```typescript
 * getDocPath('ls/documentation/uikit') // Returns "/documentation/uikit"
 * getDocPath('lc/documentation/uikit') // Returns "/documentation/uikit"
 * ```
 */
export function getDocPath(requestKey: string): string {
  if (requestKey.startsWith('ls/') || requestKey.startsWith('lc/')) {
    return '/' + requestKey.slice(3);
  }
  return '/' + requestKey;
}

/**
 * Extract framework name from a request key.
 * The framework is the first path component after "documentation".
 *
 * @param requestKey - Request key (e.g., "ls/documentation/accelerate/vdsp")
 * @returns Framework name (e.g., "accelerate") or undefined if not found
 *
 * @example
 * ```typescript
 * extractFramework('ls/documentation/uikit/uiwindow') // Returns "uikit"
 * extractFramework('ls/other/path') // Returns undefined
 * ```
 */
export function extractFramework(requestKey: string): string | undefined {
  const match = requestKey.match(/l[sc]\/documentation\/([^/]+)/);
  return match?.[1];
}

/**
 * Get the programming language from a request key.
 *
 * @param requestKey - Request key (e.g., "ls/documentation/uikit")
 * @returns 'swift' for ls/ prefix, 'objc' for lc/ prefix
 *
 * @example
 * ```typescript
 * getLanguage('ls/documentation/uikit') // Returns 'swift'
 * getLanguage('lc/documentation/uikit') // Returns 'objc'
 * ```
 */
export function getLanguage(requestKey: string): 'swift' | 'objc' {
  return requestKey.startsWith('ls/') ? 'swift' : 'objc';
}
